apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.3.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.roles: ["data", "ingest", "master"]
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        storageClassName: default
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: LoadBalancer